from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
from ucretgoster import *
import datetime
import re


class Ui_MainWindow(object):


    def ucretGoster(self,MASA_ISMI,MASA_UCRET):
        self.window = QtWidgets.QMainWindow()
        self.ui = HataPenceresi()
        self.ui.setupUi(self.window,MASA_ISMI,MASA_UCRET)
        self.window.show()
    def ilkSayfa(self):
        self.stackedWidget.setCurrentIndex(0)
    def ikinciSayfa(self):
        self.stackedWidget.setCurrentIndex(1)

    def hesapAcBtn1(self):
        now = datetime.datetime.now()
        current_time_hour = now.strftime("%H:")
        current_time_minute=now.strftime("%M")
        self.giriszamani1.setText(str(current_time_hour+current_time_minute))
        self.masa1.setStyleSheet("background-color:green;")

    def hesapKapaBtn1(self):

        now = datetime.datetime.now()
        current_time_hour = now.strftime("%H:")
        current_time_minute = now.strftime("%M")
        self.cikiszamani1.setText(str(current_time_hour+current_time_minute))
        self.masa1.setStyleSheet("background-color:red;\n"
                                 "color:white;")

        toplamucret1=0
        toplamucret1+=(int(re.sub("[^0-9]", "", self.cikiszamani1.text()))-int(re.sub("[^0-9]", "", self.giriszamani1.text())))*0.5
        for r in range(self.table1.rowCount()):
            toplamucret1+=int(self.table1.item(r, 1).text())

        self.toplam1.setText(str(toplamucret1))

        self.ucretGoster("1",str(toplamucret1))
        self.toplam1.setText("")
        self.giriszamani1.setText("MASA HENÜZ AÇILMADI")
        self.cikiszamani1.setText("MASA HENÜZ AÇILMADI")
        self.table1.setRowCount(0)
    def silBtn1(self):
        if self.table1.rowCount()>0:
            self.table1.removeRow(self.table1.rowCount()-1)
    def silBtn2(self):
        if self.table2.rowCount()>0:
            self.table2.removeRow(self.table2.rowCount()-1)
    def silBtn3(self):
        if self.table3.rowCount()>0:
            self.table3.removeRow(self.table3.rowCount()-1)

    def silBtn4(self):
        if self.table4.rowCount() > 0:
            self.table4.removeRow(self.table4.rowCount() - 1)

    def silBtn5(self):
        if self.table5.rowCount()>0:
            self.table5.removeRow(self.table5.rowCount()-1)
    def silBtn6(self):
        if self.table5_2.rowCount()>0:
            self.table5_2.removeRow(self.table5_2.rowCount()-1)


    def hesapAcBtn2(self):
        now = datetime.datetime.now()
        current_time_hour = now.strftime("%H:")
        current_time_minute=now.strftime("%M")
        self.giriszamani2.setText(str(current_time_hour+current_time_minute))
        self.masa2.setStyleSheet("background-color:green;")

    def hesapKapaBtn2(self):
        now = datetime.datetime.now()
        current_time_hour = now.strftime("%H:")
        current_time_minute = now.strftime("%M")
        self.cikiszamani2.setText(str(current_time_hour+current_time_minute))
        self.masa2.setStyleSheet("background-color:red;\n"
                                 "color:white;")
        toplamucret2 = 0
        toplamucret2+=(int(re.sub("[^0-9]", "", self.cikiszamani2.text()))-int(re.sub("[^0-9]", "", self.giriszamani2.text())))*0.5
        for r in range(self.table2.rowCount()):
            toplamucret2+=int(self.table2.item(r, 1).text())
        self.toplam2.setText(str(toplamucret2))

        self.ucretGoster("2", str(toplamucret2))
        self.toplam2.setText("")
        self.giriszamani2.setText("MASA HENÜZ AÇILMADI")
        self.cikiszamani2.setText("MASA HENÜZ AÇILMADI")
        self.table2.setRowCount(0)



    def hesapAcBtn3(self):
        now = datetime.datetime.now()
        current_time_hour = now.strftime("%H:")
        current_time_minute=now.strftime("%M")
        self.giriszamani3.setText(str(current_time_hour+current_time_minute))
        self.masa3.setStyleSheet("background-color:green;")

    def hesapKapaBtn3(self):
        now = datetime.datetime.now()
        current_time_hour = now.strftime("%H:")
        current_time_minute = now.strftime("%M")
        self.cikiszamani3.setText(str(current_time_hour+current_time_minute))
        self.masa3.setStyleSheet("background-color:red;\n"
                                 "color:white;")
        toplamucret3 = 0
        toplamucret3+=(int(re.sub("[^0-9]", "", self.cikiszamani3.text()))-int(re.sub("[^0-9]", "", self.giriszamani3.text())))*0.5
        for r in range(self.table3.rowCount()):
            toplamucret3+=int(self.table3.item(r, 1).text())
        self.toplam3.setText(str(toplamucret3))
        self.ucretGoster("3", str(toplamucret3))
        self.toplam3.setText("")
        self.giriszamani3.setText("MASA HENÜZ AÇILMADI")
        self.cikiszamani3.setText("MASA HENÜZ AÇILMADI")
        self.table3.setRowCount(0)


    def hesapAcBtn4(self):
        now = datetime.datetime.now()
        current_time_hour = now.strftime("%H:")
        current_time_minute=now.strftime("%M")
        self.giriszamani4.setText(str(current_time_hour+current_time_minute))
        self.masa4.setStyleSheet("background-color:green;")

    def hesapKapaBtn4(self):
        now = datetime.datetime.now()
        current_time_hour = now.strftime("%H:")
        current_time_minute = now.strftime("%M")
        self.cikiszamani4.setText(str(current_time_hour+current_time_minute))
        self.masa4.setStyleSheet("background-color:red;\n"
                                 "color:white;")
        toplamucret4 = 0
        toplamucret4+=(int(re.sub("[^0-9]", "", self.cikiszamani4.text()))-int(re.sub("[^0-9]", "", self.giriszamani4.text())))*0.5
        for r in range(self.table4.rowCount()):
            toplamucret4+=int(self.table4.item(r, 1).text())
        self.toplam4.setText(str(toplamucret4))
        self.ucretGoster("4", str(toplamucret4))
        self.toplam4.setText("")
        self.giriszamani4.setText("MASA HENÜZ AÇILMADI")
        self.cikiszamani4.setText("MASA HENÜZ AÇILMADI")
        self.table4.setRowCount(0)


    def hesapAcBtn5(self):
        now = datetime.datetime.now()
        current_time_hour = now.strftime("%H:")
        current_time_minute=now.strftime("%M")
        self.giriszamani5.setText(str(current_time_hour+current_time_minute))
        self.masa5.setStyleSheet("background-color:green;")

    def hesapKapaBtn5(self):
        now = datetime.datetime.now()
        current_time_hour = now.strftime("%H:")
        current_time_minute = now.strftime("%M")
        self.cikiszamani5.setText(str(current_time_hour+current_time_minute))
        self.masa5.setStyleSheet("background-color:red;\n"
                                 "color:white;")
        toplamucret5 = 0
        toplamucret5+=(int(re.sub("[^0-9]", "", self.cikiszamani5.text()))-int(re.sub("[^0-9]", "", self.giriszamani5.text())))*0.5
        for r in range(self.table5.rowCount()):
            toplamucret5+=int(self.table5.item(r, 1).text())
        self.toplam5.setText(str(toplamucret5))
        self.ucretGoster("5", str(toplamucret5))
        self.toplam5.setText("")
        self.giriszamani5.setText("MASA HENÜZ AÇILMADI")
        self.cikiszamani5.setText("MASA HENÜZ AÇILMADI")
        self.table5.setRowCount(0)

    def hesapAcBtn6(self):
        now = datetime.datetime.now()
        current_time_hour = now.strftime("%H:")
        current_time_minute=now.strftime("%M")
        self.giriszamani6.setText(str(current_time_hour+current_time_minute))
        self.masa6.setStyleSheet("background-color:green;")


    def hesapKapaBtn6(self):
        now = datetime.datetime.now()
        current_time_hour = now.strftime("%H:")
        current_time_minute = now.strftime("%M")
        self.cikiszamani6.setText(str(current_time_hour+current_time_minute))
        self.masa6.setStyleSheet("background-color:red;\n"
                                 "color:white;")
        toplamucret6 = 0
        toplamucret6+=(int(re.sub("[^0-9]", "", self.cikiszamani6.text()))-int(re.sub("[^0-9]", "", self.giriszamani6.text())))*0.5
        for r in range(self.table5_2.rowCount()):
            toplamucret6+=int(self.table5_2.item(r, 1).text())
        self.toplam6.setText(str(toplamucret6))
        self.ucretGoster("6", str(toplamucret6))
        self.toplam6.setText("")
        self.giriszamani6.setText("MASA HENÜZ AÇILMADI")
        self.cikiszamani6.setText("MASA HENÜZ AÇILMADI")
        self.table5_2.setRowCount(0)



    def cayEkle1(self):
        name="Çay"
        price="5"
        rowCount=self.table1.rowCount()
        self.table1.insertRow(rowCount)
        self.table1.setItem(rowCount,0,QTableWidgetItem(name))
        self.table1.setItem(rowCount,1,QTableWidgetItem(price))

    def tostEkle1(self):
        name="Tost"
        price="12"
        rowCount=self.table1.rowCount()
        self.table1.insertRow(rowCount)
        self.table1.setItem(rowCount,0,QTableWidgetItem(name))
        self.table1.setItem(rowCount,1,QTableWidgetItem(price))
    def kolaEkle1(self):
        name="Kola"
        price="7"
        rowCount=self.table1.rowCount()
        self.table1.insertRow(rowCount)
        self.table1.setItem(rowCount,0,QTableWidgetItem(name))
        self.table1.setItem(rowCount,1,QTableWidgetItem(price))

    def kahveEkle1(self):
        name="Kahve"
        price="15"
        rowCount=self.table1.rowCount()
        self.table1.insertRow(rowCount)
        self.table1.setItem(rowCount,0,QTableWidgetItem(name))
        self.table1.setItem(rowCount,1,QTableWidgetItem(price))


    def cayEkle2(self):
        name="Çay"
        price="5"
        rowCount=self.table1.rowCount()
        self.table2.insertRow(rowCount)
        self.table2.setItem(rowCount,0,QTableWidgetItem(name))
        self.table2.setItem(rowCount,1,QTableWidgetItem(price))

    def tostEkle2(self):
        name="Tost"
        price="12"
        rowCount=self.table1.rowCount()
        self.table2.insertRow(rowCount)
        self.table2.setItem(rowCount,0,QTableWidgetItem(name))
        self.table2.setItem(rowCount,1,QTableWidgetItem(price))
    def kolaEkle2(self):
        name="Kola"
        price="7"
        rowCount=self.table1.rowCount()
        self.table2.insertRow(rowCount)
        self.table2.setItem(rowCount,0,QTableWidgetItem(name))
        self.table2.setItem(rowCount,1,QTableWidgetItem(price))

    def kahveEkle2(self):
        name="Kahve"
        price="15"
        rowCount=self.table1.rowCount()
        self.table2.insertRow(rowCount)
        self.table2.setItem(rowCount,0,QTableWidgetItem(name))
        self.table2.setItem(rowCount,1,QTableWidgetItem(price))

    def cayEkle3(self):
        name="Çay"
        price="5"
        rowCount=self.table1.rowCount()
        self.table3.insertRow(rowCount)
        self.table3.setItem(rowCount,0,QTableWidgetItem(name))
        self.table3.setItem(rowCount,1,QTableWidgetItem(price))

    def tostEkle3(self):
        name="Tost"
        price="12"
        rowCount=self.table1.rowCount()
        self.table3.insertRow(rowCount)
        self.table3.setItem(rowCount,0,QTableWidgetItem(name))
        self.table3.setItem(rowCount,1,QTableWidgetItem(price))
    def kolaEkle3(self):
        name="Kola"
        price="7"
        rowCount=self.table1.rowCount()
        self.table3.insertRow(rowCount)
        self.table3.setItem(rowCount,0,QTableWidgetItem(name))
        self.table3.setItem(rowCount,1,QTableWidgetItem(price))

    def kahveEkle3(self):
        name="Kahve"
        price="15"
        rowCount=self.table1.rowCount()
        self.table3.insertRow(rowCount)
        self.table3.setItem(rowCount,0,QTableWidgetItem(name))
        self.table3.setItem(rowCount,1,QTableWidgetItem(price))

    def cayEkle4(self):
        name="Çay"
        price="5"
        rowCount=self.table1.rowCount()
        self.table4.insertRow(rowCount)
        self.table4.setItem(rowCount,0,QTableWidgetItem(name))
        self.table4.setItem(rowCount,1,QTableWidgetItem(price))

    def tostEkle4(self):
        name="Tost"
        price="12"
        rowCount=self.table1.rowCount()
        self.table4.insertRow(rowCount)
        self.table4.setItem(rowCount,0,QTableWidgetItem(name))
        self.table4.setItem(rowCount,1,QTableWidgetItem(price))
    def kolaEkle4(self):
        name="Kola"
        price="7"
        rowCount=self.table1.rowCount()
        self.table4.insertRow(rowCount)
        self.table4.setItem(rowCount,0,QTableWidgetItem(name))
        self.table4.setItem(rowCount,1,QTableWidgetItem(price))

    def kahveEkle4(self):
        name="Kahve"
        price="15"
        rowCount=self.table1.rowCount()
        self.table4.insertRow(rowCount)
        self.table4.setItem(rowCount,0,QTableWidgetItem(name))
        self.table4.setItem(rowCount,1,QTableWidgetItem(price))


    def cayEkle5(self):
        name="Çay"
        price="5"
        rowCount=self.table1.rowCount()
        self.table5.insertRow(rowCount)
        self.table5.setItem(rowCount,0,QTableWidgetItem(name))
        self.table5.setItem(rowCount,1,QTableWidgetItem(price))

    def tostEkle5(self):
        name="Tost"
        price="12"
        rowCount=self.table1.rowCount()
        self.table5.insertRow(rowCount)
        self.table5.setItem(rowCount,0,QTableWidgetItem(name))
        self.table5.setItem(rowCount,1,QTableWidgetItem(price))
    def kolaEkle5(self):
        name="Kola"
        price="7"
        rowCount=self.table1.rowCount()
        self.table5.insertRow(rowCount)
        self.table5.setItem(rowCount,0,QTableWidgetItem(name))
        self.table5.setItem(rowCount,1,QTableWidgetItem(price))

    def kahveEkle5(self):
        name="Kahve"
        price="15"
        rowCount=self.table1.rowCount()
        self.table5.insertRow(rowCount)
        self.table5.setItem(rowCount,0,QTableWidgetItem(name))
        self.table5.setItem(rowCount,1,QTableWidgetItem(price))


    def cayEkle6(self):
        name="Çay"
        price="5"
        rowCount=self.table1.rowCount()
        self.table5_2.insertRow(rowCount)
        self.table5_2.setItem(rowCount,0,QTableWidgetItem(name))
        self.table5_2.setItem(rowCount,1,QTableWidgetItem(price))

    def tostEkle6(self):
        name="Tost"
        price="12"
        rowCount=self.table1.rowCount()
        self.table5_2.insertRow(rowCount)
        self.table5_2.setItem(rowCount,0,QTableWidgetItem(name))
        self.table5_2.setItem(rowCount,1,QTableWidgetItem(price))
    def kolaEkle6(self):
        name="Kola"
        price="7"
        rowCount=self.table1.rowCount()
        self.table5_2.insertRow(rowCount)
        self.table5_2.setItem(rowCount,0,QTableWidgetItem(name))
        self.table5_2.setItem(rowCount,1,QTableWidgetItem(price))

    def kahveEkle6(self):
        name="Kahve"
        price="15"
        rowCount=self.table1.rowCount()
        self.table5_2.insertRow(rowCount)
        self.table5_2.setItem(rowCount,0,QTableWidgetItem(name))
        self.table5_2.setItem(rowCount,1,QTableWidgetItem(price))


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(990, 701)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_32 = QtWidgets.QFrame(self.frame_5)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_9 = QtWidgets.QLabel(self.frame_32)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_19.addWidget(self.label_9)
        self.toplam1 = QtWidgets.QLabel(self.frame_32)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toplam1.setFont(font)
        self.toplam1.setObjectName("toplam1")
        self.horizontalLayout_19.addWidget(self.toplam1)
        self.verticalLayout_3.addWidget(self.frame_32)
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.hesapac1 = QtWidgets.QPushButton(self.frame_8)
        self.hesapac1.setMaximumSize(QtCore.QSize(200, 100))
        self.hesapac1.setStyleSheet("border:2px solid green;\n"
"border-radius:10px;\n"
"")
        self.hesapac1.setObjectName("hesapac1")
        self.horizontalLayout_4.addWidget(self.hesapac1)
        self.hesapkapa1 = QtWidgets.QPushButton(self.frame_8)
        self.hesapkapa1.setMaximumSize(QtCore.QSize(200, 100))
        self.hesapkapa1.setStyleSheet("border:2px solid red;\n"
"border-radius:10px;\n"
"")
        self.hesapkapa1.setObjectName("hesapkapa1")
        self.horizontalLayout_4.addWidget(self.hesapkapa1)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.masa1 = QtWidgets.QPushButton(self.frame_5)
        self.masa1.setMinimumSize(QtCore.QSize(150, 100))
        self.masa1.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.masa1.setFont(font)
        self.masa1.setStyleSheet("background-color:red;\n"
"color:white;")
        self.masa1.setObjectName("masa1")
        self.verticalLayout_3.addWidget(self.masa1, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.giriszamani1 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.giriszamani1.setFont(font)
        self.giriszamani1.setObjectName("giriszamani1")
        self.horizontalLayout_3.addWidget(self.giriszamani1)
        self.verticalLayout_2.addWidget(self.frame_6, 0, QtCore.Qt.AlignTop)
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.cikiszamani1 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cikiszamani1.setFont(font)
        self.cikiszamani1.setObjectName("cikiszamani1")
        self.horizontalLayout_5.addWidget(self.cikiszamani1)
        self.verticalLayout_2.addWidget(self.frame_9, 0, QtCore.Qt.AlignTop)
        self.cay1 = QtWidgets.QPushButton(self.frame_2)
        self.cay1.setObjectName("cay1")
        self.verticalLayout_2.addWidget(self.cay1)
        self.tost1 = QtWidgets.QPushButton(self.frame_2)
        self.tost1.setObjectName("tost1")
        self.verticalLayout_2.addWidget(self.tost1)
        self.kola1 = QtWidgets.QPushButton(self.frame_2)
        self.kola1.setObjectName("kola1")
        self.verticalLayout_2.addWidget(self.kola1)
        self.kahve1 = QtWidgets.QPushButton(self.frame_2)
        self.kahve1.setObjectName("kahve1")
        self.verticalLayout_2.addWidget(self.kahve1)
        self.sil1 = QtWidgets.QPushButton(self.frame_2)
        self.sil1.setObjectName("sil1")
        self.verticalLayout_2.addWidget(self.sil1)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_41.setSpacing(0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.table1 = QtWidgets.QTableWidget(self.frame_7)
        self.table1.setMaximumSize(QtCore.QSize(500, 300))
        self.table1.setObjectName("table1")
        self.table1.setColumnCount(2)
        self.table1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_41.addWidget(self.table1)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.page)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_33 = QtWidgets.QFrame(self.frame_11)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_11 = QtWidgets.QLabel(self.frame_33)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_20.addWidget(self.label_11)
        self.toplam2 = QtWidgets.QLabel(self.frame_33)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toplam2.setFont(font)
        self.toplam2.setObjectName("toplam2")
        self.horizontalLayout_20.addWidget(self.toplam2)
        self.verticalLayout_5.addWidget(self.frame_33)
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.hesapac2 = QtWidgets.QPushButton(self.frame_12)
        self.hesapac2.setStyleSheet("border:2px solid green;\n"
"border-radius:10px;\n"
"")
        self.hesapac2.setObjectName("hesapac2")
        self.horizontalLayout_6.addWidget(self.hesapac2)
        self.hesapkapa2 = QtWidgets.QPushButton(self.frame_12)
        self.hesapkapa2.setStyleSheet("border:2px solid red;\n"
"border-radius:10px;\n"
"")
        self.hesapkapa2.setObjectName("hesapkapa2")
        self.horizontalLayout_6.addWidget(self.hesapkapa2)
        self.verticalLayout_5.addWidget(self.frame_12)
        self.masa2 = QtWidgets.QPushButton(self.frame_11)
        self.masa2.setMinimumSize(QtCore.QSize(150, 100))
        self.masa2.setMaximumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.masa2.setFont(font)
        self.masa2.setStyleSheet("background-color:red;\n"
"color:white;")
        self.masa2.setObjectName("masa2")
        self.verticalLayout_5.addWidget(self.masa2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.frame_11)
        self.frame_13 = QtWidgets.QFrame(self.frame_10)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.giriszamani2 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.giriszamani2.setFont(font)
        self.giriszamani2.setObjectName("giriszamani2")
        self.horizontalLayout_7.addWidget(self.giriszamani2)
        self.verticalLayout_4.addWidget(self.frame_13, 0, QtCore.Qt.AlignTop)
        self.frame_14 = QtWidgets.QFrame(self.frame_10)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.cikiszamani2 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cikiszamani2.setFont(font)
        self.cikiszamani2.setObjectName("cikiszamani2")
        self.horizontalLayout_8.addWidget(self.cikiszamani2)
        self.verticalLayout_4.addWidget(self.frame_14, 0, QtCore.Qt.AlignTop)
        self.cay2 = QtWidgets.QPushButton(self.frame_10)
        self.cay2.setObjectName("cay2")
        self.verticalLayout_4.addWidget(self.cay2)
        self.tost2 = QtWidgets.QPushButton(self.frame_10)
        self.tost2.setObjectName("tost2")
        self.verticalLayout_4.addWidget(self.tost2)
        self.kola2 = QtWidgets.QPushButton(self.frame_10)
        self.kola2.setObjectName("kola2")
        self.verticalLayout_4.addWidget(self.kola2)
        self.kahve2 = QtWidgets.QPushButton(self.frame_10)
        self.kahve2.setObjectName("kahve2")
        self.verticalLayout_4.addWidget(self.kahve2)
        self.sil2 = QtWidgets.QPushButton(self.frame_10)
        self.sil2.setObjectName("sil2")
        self.verticalLayout_4.addWidget(self.sil2)
        self.frame_15 = QtWidgets.QFrame(self.frame_10)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_42.setSpacing(0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.table2 = QtWidgets.QTableWidget(self.frame_15)
        self.table2.setMaximumSize(QtCore.QSize(500, 300))
        self.table2.setObjectName("table2")
        self.table2.setColumnCount(2)
        self.table2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_42.addWidget(self.table2)
        self.verticalLayout_4.addWidget(self.frame_15)
        self.verticalLayout_6.addWidget(self.frame_10)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.page)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_16 = QtWidgets.QFrame(self.frame_4)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.sonrakisayfabtn = QtWidgets.QPushButton(self.frame_17)
        self.sonrakisayfabtn.setObjectName("sonrakisayfabtn")
        self.verticalLayout_8.addWidget(self.sonrakisayfabtn)
        self.frame_34 = QtWidgets.QFrame(self.frame_17)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_13 = QtWidgets.QLabel(self.frame_34)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_21.addWidget(self.label_13)
        self.toplam3 = QtWidgets.QLabel(self.frame_34)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toplam3.setFont(font)
        self.toplam3.setObjectName("toplam3")
        self.horizontalLayout_21.addWidget(self.toplam3)
        self.verticalLayout_8.addWidget(self.frame_34, 0, QtCore.Qt.AlignTop)
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.hesapac3 = QtWidgets.QPushButton(self.frame_18)
        self.hesapac3.setStyleSheet("border:2px solid green;\n"
"border-radius:10px;\n"
"")
        self.hesapac3.setObjectName("hesapac3")
        self.horizontalLayout_9.addWidget(self.hesapac3)
        self.hesapkapa3 = QtWidgets.QPushButton(self.frame_18)
        self.hesapkapa3.setStyleSheet("border:2px solid red;\n"
"border-radius:10px;\n"
"")
        self.hesapkapa3.setObjectName("hesapkapa3")
        self.horizontalLayout_9.addWidget(self.hesapkapa3)
        self.verticalLayout_8.addWidget(self.frame_18)
        self.masa3 = QtWidgets.QPushButton(self.frame_17)
        self.masa3.setMinimumSize(QtCore.QSize(150, 100))
        self.masa3.setMaximumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.masa3.setFont(font)
        self.masa3.setStyleSheet("background-color:red;\n"
"color:white;")
        self.masa3.setObjectName("masa3")
        self.verticalLayout_8.addWidget(self.masa3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_7.addWidget(self.frame_17)
        self.frame_19 = QtWidgets.QFrame(self.frame_16)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.giriszamani3 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.giriszamani3.setFont(font)
        self.giriszamani3.setObjectName("giriszamani3")
        self.horizontalLayout_10.addWidget(self.giriszamani3)
        self.verticalLayout_7.addWidget(self.frame_19, 0, QtCore.Qt.AlignTop)
        self.frame_20 = QtWidgets.QFrame(self.frame_16)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.cikiszamani3 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cikiszamani3.setFont(font)
        self.cikiszamani3.setObjectName("cikiszamani3")
        self.horizontalLayout_11.addWidget(self.cikiszamani3)
        self.verticalLayout_7.addWidget(self.frame_20, 0, QtCore.Qt.AlignTop)
        self.cay3 = QtWidgets.QPushButton(self.frame_16)
        self.cay3.setObjectName("cay3")
        self.verticalLayout_7.addWidget(self.cay3)
        self.tost3 = QtWidgets.QPushButton(self.frame_16)
        self.tost3.setObjectName("tost3")
        self.verticalLayout_7.addWidget(self.tost3)
        self.kola3 = QtWidgets.QPushButton(self.frame_16)
        self.kola3.setObjectName("kola3")
        self.verticalLayout_7.addWidget(self.kola3)
        self.kahve3 = QtWidgets.QPushButton(self.frame_16)
        self.kahve3.setObjectName("kahve3")
        self.verticalLayout_7.addWidget(self.kahve3)
        self.sil3 = QtWidgets.QPushButton(self.frame_16)
        self.sil3.setObjectName("sil3")
        self.verticalLayout_7.addWidget(self.sil3)
        self.frame_21 = QtWidgets.QFrame(self.frame_16)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_43.setSpacing(0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.table3 = QtWidgets.QTableWidget(self.frame_21)
        self.table3.setMaximumSize(QtCore.QSize(500, 300))
        self.table3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table3.setObjectName("table3")
        self.table3.setColumnCount(2)
        self.table3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table3.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_43.addWidget(self.table3)
        self.verticalLayout_7.addWidget(self.frame_21)
        self.horizontalLayout_12.addWidget(self.frame_16)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_22 = QtWidgets.QFrame(self.page_2)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame_25 = QtWidgets.QFrame(self.frame_22)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_26 = QtWidgets.QFrame(self.frame_25)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_27 = QtWidgets.QFrame(self.frame_26)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_35 = QtWidgets.QFrame(self.frame_27)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_10 = QtWidgets.QLabel(self.frame_35)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_22.addWidget(self.label_10)
        self.toplam4 = QtWidgets.QLabel(self.frame_35)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toplam4.setFont(font)
        self.toplam4.setObjectName("toplam4")
        self.horizontalLayout_22.addWidget(self.toplam4)
        self.verticalLayout_10.addWidget(self.frame_35)
        self.frame_28 = QtWidgets.QFrame(self.frame_27)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.hesapac4 = QtWidgets.QPushButton(self.frame_28)
        self.hesapac4.setStyleSheet("border:2px solid green;\n"
"border-radius:10px;\n"
"")
        self.hesapac4.setObjectName("hesapac4")
        self.horizontalLayout_15.addWidget(self.hesapac4)
        self.hesapkapa4 = QtWidgets.QPushButton(self.frame_28)
        self.hesapkapa4.setStyleSheet("border:2px solid red;\n"
"border-radius:10px;\n"
"")
        self.hesapkapa4.setObjectName("hesapkapa4")
        self.horizontalLayout_15.addWidget(self.hesapkapa4)
        self.verticalLayout_10.addWidget(self.frame_28)
        self.masa4 = QtWidgets.QPushButton(self.frame_27)
        self.masa4.setMinimumSize(QtCore.QSize(150, 100))
        self.masa4.setMaximumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.masa4.setFont(font)
        self.masa4.setStyleSheet("background-color:red;\n"
"color:white;")
        self.masa4.setObjectName("masa4")
        self.verticalLayout_10.addWidget(self.masa4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_9.addWidget(self.frame_27)
        self.frame_29 = QtWidgets.QFrame(self.frame_26)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_7 = QtWidgets.QLabel(self.frame_29)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_16.addWidget(self.label_7)
        self.giriszamani4 = QtWidgets.QLabel(self.frame_29)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.giriszamani4.setFont(font)
        self.giriszamani4.setObjectName("giriszamani4")
        self.horizontalLayout_16.addWidget(self.giriszamani4)
        self.verticalLayout_9.addWidget(self.frame_29, 0, QtCore.Qt.AlignTop)
        self.frame_30 = QtWidgets.QFrame(self.frame_26)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_8 = QtWidgets.QLabel(self.frame_30)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_17.addWidget(self.label_8)
        self.cikiszamani4 = QtWidgets.QLabel(self.frame_30)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cikiszamani4.setFont(font)
        self.cikiszamani4.setObjectName("cikiszamani4")
        self.horizontalLayout_17.addWidget(self.cikiszamani4)
        self.verticalLayout_9.addWidget(self.frame_30, 0, QtCore.Qt.AlignTop)
        self.cay4 = QtWidgets.QPushButton(self.frame_26)
        self.cay4.setObjectName("cay4")
        self.verticalLayout_9.addWidget(self.cay4)
        self.tost4 = QtWidgets.QPushButton(self.frame_26)
        self.tost4.setObjectName("tost4")
        self.verticalLayout_9.addWidget(self.tost4)
        self.kola4 = QtWidgets.QPushButton(self.frame_26)
        self.kola4.setObjectName("kola4")
        self.verticalLayout_9.addWidget(self.kola4)
        self.kahve4 = QtWidgets.QPushButton(self.frame_26)
        self.kahve4.setObjectName("kahve4")
        self.verticalLayout_9.addWidget(self.kahve4)
        self.sil4 = QtWidgets.QPushButton(self.frame_26)
        self.sil4.setObjectName("sil4")
        self.verticalLayout_9.addWidget(self.sil4)
        self.frame_31 = QtWidgets.QFrame(self.frame_26)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.table4 = QtWidgets.QTableWidget(self.frame_31)
        self.table4.setMaximumSize(QtCore.QSize(500, 300))
        self.table4.setObjectName("table4")
        self.table4.setColumnCount(2)
        self.table4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table4.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_38.addWidget(self.table4)
        self.verticalLayout_9.addWidget(self.frame_31)
        self.horizontalLayout_14.addWidget(self.frame_26)
        self.horizontalLayout_18.addWidget(self.frame_25)
        self.horizontalLayout_13.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.page_2)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.frame_36 = QtWidgets.QFrame(self.frame_23)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_36)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.frame_37 = QtWidgets.QFrame(self.frame_36)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_37)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.frame_38 = QtWidgets.QFrame(self.frame_37)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_38)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_39 = QtWidgets.QFrame(self.frame_38)
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_40 = QtWidgets.QFrame(self.frame_39)
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_12 = QtWidgets.QLabel(self.frame_40)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_25.addWidget(self.label_12)
        self.toplam5 = QtWidgets.QLabel(self.frame_40)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toplam5.setFont(font)
        self.toplam5.setObjectName("toplam5")
        self.horizontalLayout_25.addWidget(self.toplam5)
        self.verticalLayout_12.addWidget(self.frame_40)
        self.frame_41 = QtWidgets.QFrame(self.frame_39)
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_41)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.hesapac5 = QtWidgets.QPushButton(self.frame_41)
        self.hesapac5.setStyleSheet("border:2px solid green;\n"
"border-radius:10px;\n"
"")
        self.hesapac5.setObjectName("hesapac5")
        self.horizontalLayout_26.addWidget(self.hesapac5)
        self.hesapkapa5 = QtWidgets.QPushButton(self.frame_41)
        self.hesapkapa5.setStyleSheet("border:2px solid red;\n"
"border-radius:10px;\n"
"")
        self.hesapkapa5.setObjectName("hesapkapa5")
        self.horizontalLayout_26.addWidget(self.hesapkapa5)
        self.verticalLayout_12.addWidget(self.frame_41)
        self.masa5 = QtWidgets.QPushButton(self.frame_39)
        self.masa5.setMinimumSize(QtCore.QSize(150, 100))
        self.masa5.setMaximumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.masa5.setFont(font)
        self.masa5.setStyleSheet("background-color:red;\n"
"color:white;")
        self.masa5.setObjectName("masa5")
        self.verticalLayout_12.addWidget(self.masa5, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_11.addWidget(self.frame_39)
        self.frame_42 = QtWidgets.QFrame(self.frame_38)
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_42)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_14 = QtWidgets.QLabel(self.frame_42)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_27.addWidget(self.label_14)
        self.giriszamani5 = QtWidgets.QLabel(self.frame_42)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.giriszamani5.setFont(font)
        self.giriszamani5.setObjectName("giriszamani5")
        self.horizontalLayout_27.addWidget(self.giriszamani5)
        self.verticalLayout_11.addWidget(self.frame_42, 0, QtCore.Qt.AlignTop)
        self.frame_43 = QtWidgets.QFrame(self.frame_38)
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_43)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_15 = QtWidgets.QLabel(self.frame_43)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_28.addWidget(self.label_15)
        self.cikiszamani5 = QtWidgets.QLabel(self.frame_43)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cikiszamani5.setFont(font)
        self.cikiszamani5.setObjectName("cikiszamani5")
        self.horizontalLayout_28.addWidget(self.cikiszamani5)
        self.verticalLayout_11.addWidget(self.frame_43, 0, QtCore.Qt.AlignTop)
        self.cay5 = QtWidgets.QPushButton(self.frame_38)
        self.cay5.setObjectName("cay5")
        self.verticalLayout_11.addWidget(self.cay5)
        self.tost5 = QtWidgets.QPushButton(self.frame_38)
        self.tost5.setObjectName("tost5")
        self.verticalLayout_11.addWidget(self.tost5)
        self.kola5 = QtWidgets.QPushButton(self.frame_38)
        self.kola5.setObjectName("kola5")
        self.verticalLayout_11.addWidget(self.kola5)
        self.kahve5 = QtWidgets.QPushButton(self.frame_38)
        self.kahve5.setObjectName("kahve5")
        self.verticalLayout_11.addWidget(self.kahve5)
        self.sil5 = QtWidgets.QPushButton(self.frame_38)
        self.sil5.setObjectName("sil5")
        self.verticalLayout_11.addWidget(self.sil5)
        self.frame_44 = QtWidgets.QFrame(self.frame_38)
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.frame_44)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.table5 = QtWidgets.QTableWidget(self.frame_44)
        self.table5.setMaximumSize(QtCore.QSize(500, 300))
        self.table5.setObjectName("table5")
        self.table5.setColumnCount(2)
        self.table5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table5.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_39.addWidget(self.table5)
        self.verticalLayout_11.addWidget(self.frame_44)
        self.horizontalLayout_24.addWidget(self.frame_38)
        self.horizontalLayout_23.addWidget(self.frame_37)
        self.horizontalLayout_29.addWidget(self.frame_36)
        self.horizontalLayout_13.addWidget(self.frame_23)
        self.frame_24 = QtWidgets.QFrame(self.page_2)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setSpacing(0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.frame_45 = QtWidgets.QFrame(self.frame_24)
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_45)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.frame_46 = QtWidgets.QFrame(self.frame_45)
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_46)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.frame_47 = QtWidgets.QFrame(self.frame_46)
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_47)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.frame_48 = QtWidgets.QFrame(self.frame_47)
        self.frame_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_48)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_49 = QtWidgets.QFrame(self.frame_48)
        self.frame_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_49.setObjectName("frame_49")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_49)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.oncekisayfabtn = QtWidgets.QPushButton(self.frame_49)
        self.oncekisayfabtn.setObjectName("oncekisayfabtn")
        self.verticalLayout_14.addWidget(self.oncekisayfabtn)
        self.frame_50 = QtWidgets.QFrame(self.frame_49)
        self.frame_50.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_50.setObjectName("frame_50")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_50)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_16 = QtWidgets.QLabel(self.frame_50)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_33.addWidget(self.label_16)
        self.toplam6 = QtWidgets.QLabel(self.frame_50)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toplam6.setFont(font)
        self.toplam6.setObjectName("toplam6")
        self.horizontalLayout_33.addWidget(self.toplam6)
        self.verticalLayout_14.addWidget(self.frame_50)
        self.frame_51 = QtWidgets.QFrame(self.frame_49)
        self.frame_51.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_51)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.hesapac6 = QtWidgets.QPushButton(self.frame_51)
        self.hesapac6.setStyleSheet("border:2px solid green;\n"
"border-radius:10px;\n"
"")
        self.hesapac6.setObjectName("hesapac6")
        self.horizontalLayout_34.addWidget(self.hesapac6)
        self.hesapkapa6 = QtWidgets.QPushButton(self.frame_51)
        self.hesapkapa6.setStyleSheet("border:2px solid red;\n"
"border-radius:10px;\n"
"")
        self.hesapkapa6.setObjectName("hesapkapa6")
        self.horizontalLayout_34.addWidget(self.hesapkapa6)
        self.verticalLayout_14.addWidget(self.frame_51)
        self.masa6 = QtWidgets.QPushButton(self.frame_49)
        self.masa6.setMinimumSize(QtCore.QSize(150, 100))
        self.masa6.setMaximumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.masa6.setFont(font)
        self.masa6.setStyleSheet("background-color:red;\n"
"color:white;")
        self.masa6.setObjectName("masa6")
        self.verticalLayout_14.addWidget(self.masa6, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_13.addWidget(self.frame_49)
        self.frame_52 = QtWidgets.QFrame(self.frame_48)
        self.frame_52.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_52.setObjectName("frame_52")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.frame_52)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_17 = QtWidgets.QLabel(self.frame_52)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_35.addWidget(self.label_17)
        self.giriszamani6 = QtWidgets.QLabel(self.frame_52)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.giriszamani6.setFont(font)
        self.giriszamani6.setObjectName("giriszamani6")
        self.horizontalLayout_35.addWidget(self.giriszamani6)
        self.verticalLayout_13.addWidget(self.frame_52, 0, QtCore.Qt.AlignTop)
        self.frame_53 = QtWidgets.QFrame(self.frame_48)
        self.frame_53.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_53.setObjectName("frame_53")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.frame_53)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_18 = QtWidgets.QLabel(self.frame_53)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_36.addWidget(self.label_18)
        self.cikiszamani6 = QtWidgets.QLabel(self.frame_53)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cikiszamani6.setFont(font)
        self.cikiszamani6.setObjectName("cikiszamani6")
        self.horizontalLayout_36.addWidget(self.cikiszamani6)
        self.verticalLayout_13.addWidget(self.frame_53, 0, QtCore.Qt.AlignTop)
        self.cay6 = QtWidgets.QPushButton(self.frame_48)
        self.cay6.setObjectName("cay6")
        self.verticalLayout_13.addWidget(self.cay6)
        self.tost6 = QtWidgets.QPushButton(self.frame_48)
        self.tost6.setObjectName("tost6")
        self.verticalLayout_13.addWidget(self.tost6)
        self.kola6 = QtWidgets.QPushButton(self.frame_48)
        self.kola6.setObjectName("kola6")
        self.verticalLayout_13.addWidget(self.kola6)
        self.kahve6 = QtWidgets.QPushButton(self.frame_48)
        self.kahve6.setObjectName("kahve6")
        self.verticalLayout_13.addWidget(self.kahve6)
        self.sil6 = QtWidgets.QPushButton(self.frame_48)
        self.sil6.setObjectName("sil6")
        self.verticalLayout_13.addWidget(self.sil6)
        self.frame_54 = QtWidgets.QFrame(self.frame_48)
        self.frame_54.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_54.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_54.setObjectName("frame_54")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.frame_54)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.table5_2 = QtWidgets.QTableWidget(self.frame_54)
        self.table5_2.setMinimumSize(QtCore.QSize(200, 100))
        self.table5_2.setMaximumSize(QtCore.QSize(500, 300))
        self.table5_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.table5_2.setObjectName("table5_2")
        self.table5_2.setColumnCount(2)
        self.table5_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table5_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table5_2.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_40.addWidget(self.table5_2)
        self.verticalLayout_13.addWidget(self.frame_54)
        self.horizontalLayout_32.addWidget(self.frame_48)
        self.horizontalLayout_31.addWidget(self.frame_47)
        self.horizontalLayout_30.addWidget(self.frame_46)
        self.horizontalLayout_37.addWidget(self.frame_45)
        self.horizontalLayout_13.addWidget(self.frame_24)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.hesapac1.clicked.connect(self.hesapAcBtn1)
        self.hesapkapa1.clicked.connect(self.hesapKapaBtn1)

        self.hesapac2.clicked.connect(self.hesapAcBtn2)
        self.hesapkapa2.clicked.connect(self.hesapKapaBtn2)

        self.hesapac3.clicked.connect(self.hesapAcBtn3)
        self.hesapkapa3.clicked.connect(self.hesapKapaBtn3)

        self.hesapac4.clicked.connect(self.hesapAcBtn4)
        self.hesapkapa4.clicked.connect(self.hesapKapaBtn4)

        self.hesapac5.clicked.connect(self.hesapAcBtn5)
        self.hesapkapa5.clicked.connect(self.hesapKapaBtn5)

        self.hesapac6.clicked.connect(self.hesapAcBtn6)
        self.hesapkapa6.clicked.connect(self.hesapKapaBtn6)

        self.oncekisayfabtn.clicked.connect(self.ilkSayfa)
        self.sonrakisayfabtn.clicked.connect(self.ikinciSayfa)

        self.cay1.clicked.connect(self.cayEkle1)
        self.tost1.clicked.connect(self.tostEkle1)
        self.kola1.clicked.connect(self.kolaEkle1)
        self.kahve1.clicked.connect(self.kahveEkle1)

        self.cay2.clicked.connect(self.cayEkle2)
        self.tost2.clicked.connect(self.tostEkle2)
        self.kola2.clicked.connect(self.kolaEkle2)
        self.kahve2.clicked.connect(self.kahveEkle2)

        self.cay3.clicked.connect(self.cayEkle3)
        self.tost3.clicked.connect(self.tostEkle3)
        self.kola3.clicked.connect(self.kolaEkle3)
        self.kahve3.clicked.connect(self.kahveEkle3)

        self.cay4.clicked.connect(self.cayEkle4)
        self.tost4.clicked.connect(self.tostEkle4)
        self.kola4.clicked.connect(self.kolaEkle4)
        self.kahve4.clicked.connect(self.kahveEkle4)

        self.cay5.clicked.connect(self.cayEkle5)
        self.tost5.clicked.connect(self.tostEkle5)
        self.kola5.clicked.connect(self.kolaEkle5)
        self.kahve5.clicked.connect(self.kahveEkle5)

        self.cay6.clicked.connect(self.cayEkle6)
        self.tost6.clicked.connect(self.tostEkle6)
        self.kola6.clicked.connect(self.kolaEkle6)
        self.kahve6.clicked.connect(self.kahveEkle6)

        self.sil1.clicked.connect(self.silBtn1)
        self.sil2.clicked.connect(self.silBtn2)
        self.sil3.clicked.connect(self.silBtn3)
        self.sil4.clicked.connect(self.silBtn4)
        self.sil5.clicked.connect(self.silBtn5)
        self.sil6.clicked.connect(self.silBtn6)







        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MURAT KRAL INTERNET KAFE"))
        self.label_9.setText(_translate("MainWindow", "TOPLAM ÜCRET:"))
        self.toplam1.setText(_translate("MainWindow", "0"))
        self.hesapac1.setText(_translate("MainWindow", "HESABI AÇ"))
        self.hesapkapa1.setText(_translate("MainWindow", "HESABI KAPA"))
        self.masa1.setText(_translate("MainWindow", "Masa-1"))
        self.label.setText(_translate("MainWindow", "Giriş Zamanı:"))
        self.giriszamani1.setText(_translate("MainWindow", "MASA HENÜZ AÇILMADI"))
        self.label_2.setText(_translate("MainWindow", "Çıkış Zamanı"))
        self.cikiszamani1.setText(_translate("MainWindow", "MASA HENÜZ AÇILMADI"))
        self.cay1.setText(_translate("MainWindow", "Çay Ekle"))
        self.tost1.setText(_translate("MainWindow", "Tost Ekle"))
        self.kola1.setText(_translate("MainWindow", "Kola Ekle"))
        self.kahve1.setText(_translate("MainWindow", "Kahve Ekle"))
        self.sil1.setText(_translate("MainWindow", "ÜRÜN KALDIR"))
        item = self.table1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ÜRÜN"))
        item = self.table1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FİYAT"))
        self.label_11.setText(_translate("MainWindow", "TOPLAM ÜCRET:"))
        self.toplam2.setText(_translate("MainWindow", "0"))
        self.hesapac2.setText(_translate("MainWindow", "HESABI AÇ"))
        self.hesapkapa2.setText(_translate("MainWindow", "HESABI KAPA"))
        self.masa2.setText(_translate("MainWindow", "Masa-2"))
        self.label_3.setText(_translate("MainWindow", "Giriş Zamanı:"))
        self.giriszamani2.setText(_translate("MainWindow", "MASA HENÜZ AÇILMADI"))
        self.label_4.setText(_translate("MainWindow", "Çıkış Zamanı"))
        self.cikiszamani2.setText(_translate("MainWindow", "MASA HENÜZ AÇILMADI"))
        self.cay2.setText(_translate("MainWindow", "Çay Ekle"))
        self.tost2.setText(_translate("MainWindow", "Tost Ekle"))
        self.kola2.setText(_translate("MainWindow", "Kola Ekle"))
        self.kahve2.setText(_translate("MainWindow", "Kahve Ekle"))
        self.sil2.setText(_translate("MainWindow", "ÜRÜN KALDIR"))
        item = self.table2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ÜRÜN"))
        item = self.table2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FİYAT"))
        self.sonrakisayfabtn.setText(_translate("MainWindow", "SONRAKİ SAYFA"))
        self.label_13.setText(_translate("MainWindow", "TOPLAM ÜCRET:"))
        self.toplam3.setText(_translate("MainWindow", "0"))
        self.hesapac3.setText(_translate("MainWindow", "HESABI AÇ"))
        self.hesapkapa3.setText(_translate("MainWindow", "HESABI KAPA"))
        self.masa3.setText(_translate("MainWindow", "Masa-3"))
        self.label_5.setText(_translate("MainWindow", "Giriş Zamanı:"))
        self.giriszamani3.setText(_translate("MainWindow", "MASA HENÜZ AÇILMADI"))
        self.label_6.setText(_translate("MainWindow", "Çıkış Zamanı"))
        self.cikiszamani3.setText(_translate("MainWindow", "MASA HENÜZ AÇILMADI"))
        self.cay3.setText(_translate("MainWindow", "Çay Ekle"))
        self.tost3.setText(_translate("MainWindow", "Tost Ekle"))
        self.kola3.setText(_translate("MainWindow", "Kola Ekle"))
        self.kahve3.setText(_translate("MainWindow", "Kahve Ekle"))
        self.sil3.setText(_translate("MainWindow", "ÜRÜN KALDIR"))
        item = self.table3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ÜRÜN"))
        item = self.table3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FİYAT"))
        self.label_10.setText(_translate("MainWindow", "TOPLAM ÜCRET"))
        self.toplam4.setText(_translate("MainWindow", "0"))
        self.hesapac4.setText(_translate("MainWindow", "HESABI AÇ"))
        self.hesapkapa4.setText(_translate("MainWindow", "HESABI KAPA"))
        self.masa4.setText(_translate("MainWindow", "Masa-4"))
        self.label_7.setText(_translate("MainWindow", "Giriş Zamanı:"))
        self.giriszamani4.setText(_translate("MainWindow", "MASA HENÜZ AÇILMADI"))
        self.label_8.setText(_translate("MainWindow", "Çıkış Zamanı"))
        self.cikiszamani4.setText(_translate("MainWindow", "MASA HENÜZ AÇILMADI"))
        self.cay4.setText(_translate("MainWindow", "Çay Ekle"))
        self.tost4.setText(_translate("MainWindow", "Tost Ekle"))
        self.kola4.setText(_translate("MainWindow", "Kola Ekle"))
        self.kahve4.setText(_translate("MainWindow", "Kahve Ekle"))
        self.sil4.setText(_translate("MainWindow", "ÜRÜN KALDIR"))
        item = self.table4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ÜRÜN"))
        item = self.table4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FİYAT"))
        self.label_12.setText(_translate("MainWindow", "TOPLAM ÜCRET"))
        self.toplam5.setText(_translate("MainWindow", "0"))
        self.hesapac5.setText(_translate("MainWindow", "HESABI AÇ"))
        self.hesapkapa5.setText(_translate("MainWindow", "HESABI KAPA"))
        self.masa5.setText(_translate("MainWindow", "Masa-5"))
        self.label_14.setText(_translate("MainWindow", "Giriş Zamanı:"))
        self.giriszamani5.setText(_translate("MainWindow", "MASA HENÜZ AÇILMADI"))
        self.label_15.setText(_translate("MainWindow", "Çıkış Zamanı"))
        self.cikiszamani5.setText(_translate("MainWindow", "MASA HENÜZ AÇILMADI"))
        self.cay5.setText(_translate("MainWindow", "Çay Ekle"))
        self.tost5.setText(_translate("MainWindow", "Tost Ekle"))
        self.kola5.setText(_translate("MainWindow", "Kola Ekle"))
        self.kahve5.setText(_translate("MainWindow", "Kahve Ekle"))
        self.sil5.setText(_translate("MainWindow", "ÜRÜN KALDIR"))
        item = self.table5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ÜRÜN"))
        item = self.table5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FİYAT"))
        self.oncekisayfabtn.setText(_translate("MainWindow", "ÖNCEKİ SAYFA"))
        self.label_16.setText(_translate("MainWindow", "TOPLAM ÜCRET"))
        self.toplam6.setText(_translate("MainWindow", "0"))
        self.hesapac6.setText(_translate("MainWindow", "HESABI AÇ"))
        self.hesapkapa6.setText(_translate("MainWindow", "HESABI KAPA"))
        self.masa6.setText(_translate("MainWindow", "Masa-6"))
        self.label_17.setText(_translate("MainWindow", "Giriş Zamanı:"))
        self.giriszamani6.setText(_translate("MainWindow", "MASA HENÜZ AÇILMADI"))
        self.label_18.setText(_translate("MainWindow", "Çıkış Zamanı"))
        self.cikiszamani6.setText(_translate("MainWindow", "MASA HENÜZ AÇILMADI"))
        self.cay6.setText(_translate("MainWindow", "Çay Ekle"))
        self.tost6.setText(_translate("MainWindow", "Tost Ekle"))
        self.kola6.setText(_translate("MainWindow", "Kola Ekle"))
        self.kahve6.setText(_translate("MainWindow", "Kahve Ekle"))
        self.sil6.setText(_translate("MainWindow", "ÜRÜN KALDIR"))
        item = self.table5_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ÜRÜN"))
        item = self.table5_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FİYAT"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
